# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: ivabus
          template: classic
          base: activity, community, repositories
          base_indepth: yes
          config_timezone: Europe/Moscow
          plugin_anilist: yes
          plugin_anilist_limit: 4
          plugin_anilist_limit_characters: 22
          plugin_anilist_medias: anime,manga
          plugin_anilist_sections: favorites
          plugin_anilist_shuffle: yes
          plugin_anilist_user: ivabus
          plugin_calendar: yes
          plugin_calendar_limit: 0
          plugin_languages: yes
          plugin_languages_analysis_timeout: 60
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_indepth: yes
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 140
          plugin_languages_recent_load: 3000
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_rss: yes
          plugin_rss_limit: 4
          plugin_rss_source: https://ivabus.dev/feed.xml
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: icons
          plugin_topics_sort: stars
          repositories: 10000
          repositories_batch: 1000
          repositories_forks: yes
